name: Chia Gaming tests

on:
  push:
    branches:
      - main
      - dev
    tags:
        - '**'
  pull_request:
    branches:
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  chia_gaming_tests:
    name: Extensive Chia Gaming tests
    permissions:
      contents: read

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Checkout chia-gaming
      uses: actions/checkout@v6
      with:
        repository: Chia-Network/chia-gaming
        path: chia-gaming
        ref: main

    - name: Replace chialisp pkg in chia-gaming
      run: |
        python3 support/change-chialisp-rev.py ${{ github.sha }} chia-gaming/Cargo.toml

    - name: Install chia-gaming dependencies
      run: |
        cd chia-gaming
        ./tools/check-build-deps.sh --install --yes

    - name: Rebuild chia-gaming chialisp
      run: |
        cp support/chia-gaming-build.rs chia-gaming/build.rs
        cd chia-gaming
        cargo build

    - name: Run chia-gaming chialisp tests
      run: |
        cd chia-gaming
        ./tools/run-clsp-tests.sh
