name: Chia Gaming tests

on:
  push:
    branches:
      - main
      - dev
    tags:
        - '**'
  pull_request:
    branches:
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  chia_gaming_tests:
    name: Extensive Chia Gaming tests
    permissions:
      contents: read

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Checkout chia-gaming
      uses: actions/checkout@v6
      with:
        repository: Chia-Network/chia-gaming
        path: chia-gaming
        ref: main

    - name: Replace chialisp pkg in chia-gaming
      run: |
        python3 support/change-chialisp-rev.py ${{ github.sha }} chia-gaming/Cargo.toml

    - name: Install chia-gaming dependencies
      run: |
        cd chia-gaming
        ./tools/check-build-deps.sh --install --yes

    - name: Rebuild chia-gaming chialisp
      run: |
        cp support/chia-gaming-build.rs chia-gaming/build.rs
        cd chia-gaming
        for file in $(find clsp -name \*.hex) ; do rm $file ; done
        cargo build
        echo generated hex files
        find clsp -name \*.hex
        echo end hex files
        rm -rf build.rs

    - name: Run chia-gaming chialisp tests
      run: |
        cd chia-gaming
        # XXX don't delete the hex files here as we just rebuilt everything.
        # XXX somehow cargo test doesn't regenerate the hex files either, so that's likely a bug?
        mv tools/run-clsp-tests.sh tools/run-clsp-tests.no
        grep -v 'xargs rm' ./tools/run-clsp-tests.no | grep -v 'cd "$REPO_ROOT"' > ./tools/run-clsp-tests.sh
        chmod +x ./tools/run-clsp-tests.sh
        ./tools/run-clsp-tests.sh
